version: 2.1

orbs:
  deepcrawl-test: deepcrawl/deepcrawl-test@<< pipeline.parameters.dev-orb-version >>
  orb-tools: circleci/orb-tools@10.0

parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: deepcrawl/deepcrawl-test
          context: orb-publishing
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - deepcrawl-test/run-build:
          context: orb-publishing
          testSuiteId: "TjAwOVRlc3RTdWl0ZTM3NjI2Ng"
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: deepcrawl/deepcrawl-test
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - deepcrawl-test/run-build
          filters:
            branches:
              only:
                - main
