version: 2.1

workflows:
  deploy:
    jobs:
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: deepcrawl/test
          context: org-global
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          filters:
            branches:
              only:
                - main
